// Tax Expats Club — 4 June 2026 participant list.
// Names have been removed for privacy: entries carry an anonymous guest id,
// plus company, role and optional taxAreas (pre-filled only where the role
// made the area unambiguous; otherwise confirmed via the check-in form).

export const ATTENDEES = [
  { id: "guest-01", name: "Guest 01", company: "inRange Solutions", role: "Director", taxAreas: ["Transfer Pricing"] },
  { id: "guest-02", name: "Guest 02", company: "Nutanix", role: "Director, International Tax", taxAreas: ["International / Pillar 2 / BEPS"] },
  { id: "guest-03", name: "Guest 03", company: "DTEK", role: "Head of TP", taxAreas: ["Transfer Pricing"] },
  { id: "guest-04", name: "Guest 04", company: "Coty", role: "Senior Manager TP", taxAreas: ["Transfer Pricing"] },
  { id: "guest-05", name: "Guest 05", company: "MBK Investment / Mitsui", role: "Tax Manager", taxAreas: [] },
  { id: "guest-06", name: "Guest 06", company: "INGKA", role: "TP Manager", taxAreas: ["Transfer Pricing"] },
  { id: "guest-07", name: "Guest 07", company: "OPPO / OnePlus", role: "Tax Manager", taxAreas: [] },
  { id: "guest-08", name: "Guest 08", company: "MGA Entertainment", role: "Tax Manager — EMEA", taxAreas: [] },
  { id: "guest-09", name: "Guest 09", company: "RHI Magnesita", role: "Head of Corporate Tax Governance", taxAreas: ["Direct / CIT"] },
  { id: "guest-10", name: "Guest 10", company: "Delta Electronics", role: "Chief Accountant, EMEA Indirect Tax", taxAreas: ["Indirect / VAT"] },
  { id: "guest-11", name: "Guest 11", company: "Under Armour", role: "Indirect Tax", taxAreas: ["Indirect / VAT"] },
  { id: "guest-12", name: "Guest 12", company: "ACT Group", role: "Senior Tax Specialist", taxAreas: [] },
  { id: "guest-13", name: "Guest 13", company: "Rabobank", role: "Tax Transfer Pricing Specialist", taxAreas: ["Transfer Pricing"] },
  { id: "guest-14", name: "Guest 14", company: "Coty", role: "TP Manager", taxAreas: ["Transfer Pricing"] },
  { id: "guest-15", name: "Guest 15", company: "SGS Group", role: "Senior Director, Tax & Business Partnering", taxAreas: [] },
  { id: "guest-16", name: "Guest 16", company: "JET", role: "Transfer Pricing", taxAreas: ["Transfer Pricing"] },
  { id: "guest-17", name: "Guest 17", company: "Digital Realty", role: "Tax professional", taxAreas: [] },
  { id: "guest-18", name: "Guest 18", company: "Waterland", role: "Tax Manager", taxAreas: [] },
  { id: "guest-19", name: "Guest 19", company: "Seagate", role: "Senior Tax Manager", taxAreas: [] },
  { id: "guest-20", name: "Guest 20", company: "Coty", role: "EMEA Tax Manager", taxAreas: [] },
  { id: "guest-21", name: "Guest 21", company: "IBFD", role: "Analyst", taxAreas: [] },
  { id: "guest-22", name: "Guest 22", company: "Delta Electronics", role: "Specialist, Finance", taxAreas: [] },
  { id: "guest-23", name: "Guest 23", company: "Danone", role: "TP Manager", taxAreas: ["Transfer Pricing"] },
  { id: "guest-24", name: "Guest 24", company: "Digital Realty", role: "VP, Tax EMEA", taxAreas: [] },
  { id: "guest-25", name: "Guest 25", company: "HelloFresh", role: "International Tax", taxAreas: [] },
  { id: "guest-26", name: "Guest 26", company: "Teva", role: "EMEA Tax Director", taxAreas: [] },
  { id: "guest-27", name: "Guest 27", company: "Hitachi Energy", role: "Tax professional", taxAreas: [] },
  { id: "guest-28", name: "Guest 28", company: "Ecco", role: "Junior VAT Accountant", taxAreas: ["Indirect / VAT"] },
  { id: "guest-29", name: "Guest 29", company: "Kubota", role: "Tax Manager", taxAreas: [] },
  { id: "guest-30", name: "Guest 30", company: "ACT Commodities", role: "Transfer Pricing", taxAreas: ["Transfer Pricing"] },
  { id: "guest-31", name: "Guest 31", company: "IKEA (Inter IKEA)", role: "Tax Advisor", taxAreas: [] },
  { id: "guest-32", name: "Guest 32", company: "Magnum Ice Cream", role: "TP Senior Manager", taxAreas: ["Transfer Pricing"] },
  { id: "guest-33", name: "Guest 33", company: "Ecco", role: "Indirect Tax Manager", taxAreas: ["Indirect / VAT"] },
  { id: "guest-34", name: "Guest 34", company: "Fertiglobe", role: "Tax professional", taxAreas: [] },
  { id: "guest-35", name: "Guest 35", company: "Sabic", role: "Tax Risk Management", taxAreas: [] },
  { id: "guest-36", name: "Guest 36", company: "Lipton", role: "CIT and TP Manager", taxAreas: ["Direct / CIT", "Transfer Pricing"] },
];
